version: '3'
service:
  staging-repnotes-ami-v2:
    build:
      context: .
    image: staging-repnotes-ami-v2
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/staging-repnotes-ami-v2/default.conf
    restart: always
    ports:
      - '3034:80'  
    
    